# This file was generated by GoReleaser. DO NOT EDIT.
cask "hal" do
  name "hal"
  desc ""
  homepage ""
  version "0.1.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hal"

  on_macos do
    on_intel do
      url "https://github.com/j-yw/hal/releases/download/v#{version}/hal_#{version}_darwin_amd64.tar.gz"
      sha256 "69a94e8ff3f8686f2637e2ab7ba438e1cec2fcdba707721b7420823b7c5d6e3a"
    end
    on_arm do
      url "https://github.com/j-yw/hal/releases/download/v#{version}/hal_#{version}_darwin_arm64.tar.gz"
      sha256 "3fdeb1a3046d5733d5bedd680a6734c66fae998d5979f690c612920399f77b2f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/j-yw/hal/releases/download/v#{version}/hal_#{version}_linux_amd64.tar.gz"
      sha256 "2ec41529caa61d90aef0839407caa608c1a538f172d772090c7c8e22c630b89f"
    end
    on_arm do
      url "https://github.com/j-yw/hal/releases/download/v#{version}/hal_#{version}_linux_arm64.tar.gz"
      sha256 "2c5a4840db737bba71b3af43ef5d69818f2e74b2069416fa870dc30f7a86f451"
    end
  end

  # No zap stanza required
end
