# This file was generated by GoReleaser. DO NOT EDIT.
cask "hal" do
  name "hal"
  desc ""
  homepage ""
  version "0.2.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hal"

  on_macos do
    on_intel do
      url "https://github.com/j-yw/hal/releases/download/v#{version}/hal_#{version}_darwin_amd64.tar.gz"
      sha256 "09ceac89311159c77b32009167071c817c069141609ea14a146bea32639eda60"
    end
    on_arm do
      url "https://github.com/j-yw/hal/releases/download/v#{version}/hal_#{version}_darwin_arm64.tar.gz"
      sha256 "464f7425c65439a79fbc3dd7e503c9fe335ac002ebbf67c130ec4a8a506845f9"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/j-yw/hal/releases/download/v#{version}/hal_#{version}_linux_amd64.tar.gz"
      sha256 "4a8a8a3f00c605e62bcb18a9505066d8a80b63cc2097da16ad756203f9c6fa89"
    end
    on_arm do
      url "https://github.com/j-yw/hal/releases/download/v#{version}/hal_#{version}_linux_arm64.tar.gz"
      sha256 "134557c8aacc56b7b05b6af764b351204c0caa12ea81d69b27abef5c974d3b2d"
    end
  end

  # No zap stanza required
end
