# This file was generated by GoReleaser. DO NOT EDIT.
cask "hal" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "4f623f0c2646c89cad3e12d5861f4634d72c301d2c49f057703f6392a7a6a9d7"
      url "https://github.com/j-yw/hal/releases/download/v#{version}/hal_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "76cc58818acdc655247889cb8af27d43b342765a32846793dbf748a856e3ad21"
      url "https://github.com/j-yw/hal/releases/download/v#{version}/hal_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "795c99f7678d693b78845a930d09bb578f6d13bee93a7ebd5b9ec898b473f55b"
      url "https://github.com/j-yw/hal/releases/download/v#{version}/hal_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "be7c7906178a4c1a32dcea92c35377aa61e3fc79363da954b5772e190b1d56af"
      url "https://github.com/j-yw/hal/releases/download/v#{version}/hal_#{version}_linux_arm64.tar.gz"
    end
  end

  name "hal"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hal"

  # No zap stanza required

end
